### ISSUE TITLE
Fluid size instead of fixed 480x270

### ISSUE THREAD

**Issue by iroller** [discourse/discourse-lazyYT#1]
Looks like youtube videos are always being embedded with 480x270px size:
https://github.com/discourse/discourse-lazyYT/blob/master/plugin.rb#L21

How about making it fluid?
Looks like lazyYT supports it pretty well:
https://github.com/tylerpearson/lazyYT
http://works.daugilas.com/lazyYT/demo/fluid.html

Thanks for the plugin!

**Comment by techAPJ** [comment]
Fixed via https://github.com/discourse/discourse/pull/3136

This plugin is now moved to: https://github.com/discourse/discourse/tree/master/plugins/lazyYT
